### ISSUE TITLE
Servlet 2.5 with XML Spring Configuration

### ISSUE THREAD

**Issue by pdorgambide** [spring-projects/spring-session#101]
I would like to integrate the spring session into an existed projects that runs on tomcat 6 (servlet 2.5) and are configured using XML spring configuration files. 
As the servlet 2.5 does not work with WebApplicationInitializer and the documentation does not show how to configure the spring-session with Spring XML configuration files (usefull for old apps) this integration  will be harder than expected.
It will be very helpfull more documentation about how integrate spring-session with legacy spring application

**Comment by artembilan** [comment]
Related SO question http://stackoverflow.com/questions/27934251/spring-messaging-xml-config-with-stomp-and-spring-sessions

**Comment by artembilan** [comment]
To this issue. I was going to show some XML config for `<websocket:broker>`, but noticed that `WebSocketHandlerDecoratorFactory` requires `ApplicationEventPublisher` as ctor arg. Would be better to implement `ApplicationEventPublisherAware` there.
Thanks

**Comment by rwinch** [comment]
@pdorgambide Thanks for creating a ticket. I agree that this is something that should be documented.

In the meantime, are you aware you can used mixed [Spring XML configuration with Spring Java Configuration](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-java-combining)?

I've also created a few additional tickets (#103 #104 #105) to make things better. Note that I have already added a complete sample for #103 at https://github.com/spring-projects/spring-session/tree/ba07c1d5620f290eb5ee8a853c748019182d8345/samples/httpsession-xml

**Comment by pdorgambide** [comment]
@rwinch  thanks a lot.
I am an Spring's caveman and It has been easier configure my legacy projects with XML: **applicationContext-session.xml**
Once time it runs, due that I use Servlet 2.5 throws the next exception: 
    java.lang.NoSuchMethodError: org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getServletContext()
HttpRequest interface have the getServletContext() since 3.0 ;o(
This challenge allow me to know more about Servlet 3.0, Spring Boot and JavaConfig and take in order to use into near future.

**Comment by rwinch** [comment]
@pdorgambide Thanks for following up. Does this mean you were able to get your application configured using XML and JavaConfig?

The `NoSuchMethodError` sounds like a bug. Spring Session should work with Servlet 2.5, but based on your description it sounds as though it is not. Can you create a new issue with a complete stacktrace?

**Comment by pdorgambide** [comment]
@rwinch I am able to get the application configured only with XML.
I will create the new issue with the complete stracktrace to let you located and fix. 
Awesome work.

**Comment by rwinch** [comment]
Closing this issue since it is now superseded by additional tickets (many of which are fixed)
